table Queues
	lineageTag: 0b033b9f-40a7-4ef2-99c1-ecc79a841f9c

	column 'Queue Key'
		dataType: int64
		lineageTag: a3084821-a733-400d-b7cd-f0ccabcf5836
		summarizeBy: none
		sourceColumn: Queue Key

	column 'Queue ID'
		dataType: string
		lineageTag: d73587c0-b2d4-4a2d-9b31-5ed35820a6d1
		summarizeBy: none
		sourceColumn: Queue ID

	column 'Queue Name'
		dataType: string
		lineageTag: bb2f8da6-56cf-4158-8025-888d5f8ae74a
		summarizeBy: none
		sourceColumn: Queue Name

	column 'SLA Target Seconds'
		dataType: int64
		lineageTag: c9fc3a80-8e77-44a5-8e0a-8f0cf8c75fc5
		summarizeBy: none
		sourceColumn: SLA Target Seconds

	column Priority
		dataType: string
		lineageTag: fff51f88-4d97-41ec-96d6-964947fbca66
		summarizeBy: none
		sourceColumn: Priority

	partition Queues = m
		mode: import
		source =
				let
					Source = Excel.Workbook(File.Contents(SourceWorkbookPath), null, true),
					#"Selected Queues sheet" = Source{[Item="Queues",Kind="Sheet"]}[Data],
					#"Promoted column headers" = Table.PromoteHeaders(#"Selected Queues sheet", [PromoteAllScalars=true]),
					#"Applied column types" = Table.TransformColumnTypes(#"Promoted column headers", {{"Queue Key", Int64.Type}, {"Queue ID", type text}, {"Queue Name", type text}, {"SLA Target Seconds", Int64.Type}, {"Priority", type text}})
				in
					#"Applied column types"

