table Calendar
	dataCategory: Time

	column 'Date Key'
		dataType: int64
		sourceColumn: Date Key
		summarizeBy: none

	column Date
		dataType: dateTime
		sourceColumn: Date
		summarizeBy: none
		formatString: yyyy-mm-dd

	column Year
		dataType: int64
		sourceColumn: Year
		summarizeBy: none

	column 'Month Number'
		dataType: int64
		sourceColumn: Month Number
		summarizeBy: none

	column 'Month Key'
		dataType: int64
		sourceColumn: Month Key
		summarizeBy: none

	column 'Month Year'
		dataType: string
		sourceColumn: Month Year
		summarizeBy: none
		sortByColumn: 'Month Key'

	column 'Month Start'
		dataType: dateTime
		sourceColumn: Month Start
		summarizeBy: none

	column 'Week Start'
		dataType: dateTime
		sourceColumn: Week Start
		summarizeBy: none

	column 'Week Label'
		dataType: string
		sourceColumn: Week Label
		summarizeBy: none
		sortByColumn: 'Week Start'

	column 'Day Name'
		dataType: string
		sourceColumn: Day Name
		summarizeBy: none

	column 'Is Workday'
		dataType: boolean
		sourceColumn: Is Workday
		summarizeBy: none

	partition 'Calendar' = m
		mode: import
		source =
			let
				Source = Excel.Workbook(File.Contents(SourceWorkbookPath), null, true),
				#"Selected Calendar sheet" = Source{[Item="Calendar",Kind="Sheet"]}[Data],
				#"Promoted column headers" = Table.PromoteHeaders(#"Selected Calendar sheet", [PromoteAllScalars=true]),
				#"Applied column types" = Table.TransformColumnTypes(#"Promoted column headers", {{"Date Key", Int64.Type}, {"Date", type date}, {"Year", Int64.Type}, {"Month Number", Int64.Type}, {"Month Key", Int64.Type}, {"Month Year", type text}, {"Month Start", type date}, {"Week Start", type date}, {"Week Label", type text}, {"Day Name", type text}, {"Is Workday", type logical}})
			in
				#"Applied column types"
